window.hjSiteSettings = window.hjSiteSettings || {"testers_widgets":[],"surveys":[],"heatmaps":[{"created_epoch_time":1469722743,"targeting":[{"negate":false,"pattern":"https:\/\/www.ten-x.com\/company\/commercial\/listings\/","match_operation":"simple","component":"url"}],"id":670716},{"created_epoch_time":1462030791,"targeting":[{"negate":false,"pattern":"https:\/\/www.ten-x.com\/company\/commercial\/financing\/","match_operation":"simple","component":"url"}],"id":501660},{"created_epoch_time":1460379910,"targeting":[{"negate":false,"pattern":"https:\/\/www.ten-x.com\/commercial\/dashboard\/buyer\/offers\/","match_operation":"starts_with","component":"url"}],"id":463022},{"created_epoch_time":1459967291,"targeting":[{"negate":false,"pattern":"https:\/\/www.ten-x.com\/commercial\/listing-details\/","match_operation":"starts_with","component":"url"}],"id":454648},{"created_epoch_time":1458627720,"targeting":[{"negate":false,"pattern":"https:\/\/www.ten-x.com\/company\/commercial\/nowcast\/","match_operation":"simple","component":"url"}],"id":427265}],"recording_capture_keystrokes":true,"polls":[],"site_id":124386,"record_targeting_rules":[],"forms":[],"record":false,"r":1.0,"deferred_page_contents":[{"targeting":[{"negate":false,"pattern":"https:\/\/www.ten-x.com\/company\/commercial\/listings\/","match_operation":"simple","component":"url"},{"negate":false,"pattern":"desktop","match_operation":"exact","component":"device"}],"id":1703944},{"targeting":[{"negate":false,"pattern":"https:\/\/www.ten-x.com\/company\/commercial\/listings\/","match_operation":"simple","component":"url"},{"negate":false,"pattern":"tablet","match_operation":"exact","component":"device"}],"id":1703943},{"targeting":[{"negate":false,"pattern":"https:\/\/www.ten-x.com\/company\/commercial\/listings\/","match_operation":"simple","component":"url"},{"negate":false,"pattern":"phone","match_operation":"exact","component":"device"}],"id":1703942}]};

window.hjBootstrap = window.hjBootstrap || function (scriptUrl) {
    var s = document.createElement('script');
    s.src = scriptUrl;
    document.getElementsByTagName('head')[0].appendChild(s);
    window.hjBootstrap = function() {};
};

hjBootstrap('https://script.hotjar.com/modules-f11f300298016929705879370045d683.js');